### ISSUE TITLE
Add user friendly messages if object is missing

### ISSUE THREAD

**Issue by i-bash** [i-bash/pg-dev1-web#2]

**Comment by i-bash** [comment]
Можно ли сказать, что сообщение зависит только от вида и имени отсутствующего объекта?

**Comment by egor-rogov** [comment]
В первом приближении - да.
Но хорошо бы еще выдавать какое-то предупреждение, если в представлении catalog_v нет всех нужных столбцов. Писать, что функциональность ограничена, потому что нет поля qty (например).

**Comment by egor-rogov** [comment]
Кажется, это одно и то же с #21

**Comment by i-bash** [comment]
Идея такая. Ловить ошибки "объект не существует" и "колонка" не существует, вытаскивать имя объекта/колонки из текста сообщения, прописать в массиве-константе дополнительные сообщения в зависимости от объекта/колонки. Минусы: зависимость от языка сообщений и от текста. Плюсы: универсальность, удобство сопровождения. Есть другие идеи?

**Comment by egor-rogov** [comment]
Ловить ошибки сложно, как мне кажется. К тому же для столбцов никакой ошибки нет: как я понял, делается select * и потом в приложении выводятся те поля, которые "опознаны" (и хорошо, что так).

Проще явно заранее проверять наличие нужных объектов отдельными вспомогательными запросами (они уже отчасти есть: check*Existence). Для каждого action-а задать явно список проверяемых объектов и сообщения. Эти проверки должы просто выводить сообщения-предупреждения, но не прерывать работу - чтобы потом при выполнении реального запроса появилось и нормальное сообщение об ошибке от базы.

**Comment by i-bash** [comment]
Наличие объекта зависит от привилегий, сообщения будут это учитывать? Например, "Функция  будет сделана в уроке 6, либо у вас нет на неё привилегий". Мне кажется, надо уже написать первый вариант списка проверок и сообщений для 7 акций.

**Comment by egor-rogov** [comment]
Привилегии там последней темой, так что, думаю, в формулировках не надо учитывать.

Попробовал накидать cписок:

- **getAuthors**
view authors_v: Представление для списка авторов будет создано в теме 9 "Взаимодействие приложения с СУБД"
- **addAuthor**
function add_author: Функция для добавления автора будет создана в теме 14 "Выполнение запросов"
- **getBooks, getCatalog**
view catalog_v: Представление для списка книг будет создано в теме 9 "Взаимодействие приложения с СУБД"
- **addBook**
function add_book: Функция для добавления книги будет создана в теме 17 "Массивы"
- **orderBook**
trigger instead of update on catalog_v: Триггер для обновления представления будет создан в теме 19 "Триггеры"
(можно завязаться и на имя триггера update_catalog_trigger, но лучше бы не надо)
- **findBooks**
function get_catalog: Функция для поиска книг будет создана в теме 11 "Составные типы и табличные функции"
- **buyBook**
function buy_book: Функция для покупки книги  будет создана в теме 14 "Выполнение запросов"

Еще там какой-то экшн test... Бэкдор (:

Плюс к этому надо смотреть на список столбцов, которые вытянулись в get_catalog() и catalog_v. Если среди них нет onhand_qty, то сообщить: Столбец наличного количества будет добавлен в теме 11 "Составные типы и табличные функции".
С остальными столбцами, пожалуй, нет смысла заморачиваться - и так будет видно, что чего-то не выводится.

**Comment by i-bash** [comment]
Немного изменил интерфейс.
Заменил акцию getBooks на getCatalog (они идентичны), бэкдор убрал ).
Реализовал проверку отношений, функций и триггеров с выдачей сообщений.
Осталась проверка столбца onhand_qty.

**Comment by i-bash** [comment]
Со столбцами всё немного сложнее.

1. В книгах, наверное, проверять столбцы не надо.

2. В каталоге, видимо, надо проверять наличие столбца onhand_qty в представлении catalog_v или в результате запроса и, если его нет, то выводить в колонке "Наличие" пустые значения.

3. В магазине при вызове get_catalog() получаю обычный массив, да и то если в результате есть хотя бы одна строка. Поэтому могу проверить только количество столбцов. Как узнать, есть ли столбец с заданным именем (onhand_qty), пока не знаю.

**Comment by egor-rogov** [comment]
Хм, тогда лучше всего делать не `select *`, а `select book_id, display_name, onhand_qty`. А если ломается, пробовать `select book_id, display_name`.
А то ведь черт знает что получиться может.

**Comment by i-bash** [comment]
Не очень понял. С запросами к таблицам и представлениям проблем нет, получаю для каждой строки ассоциативный массив с ключами - именами столбцов. 

Проблема только с функцией RETURNS TABLE. Запрос
**select get_catalog(
   author_name=>$1,
   book_title=>$2,
   in_stock=>$3
) result**
выдаёт один столбец с именем result, в котором находятся строковые значения типа
**(2,"Муму. Тургенев И. С.")**.
То есть в этом случае имена столбцов не передаются.

**Comment by egor-rogov** [comment]
А-а, понял. `select * from get_catalog(...);` должно помочь.
Но вообще в целом `select *` нехорошая практика...

**Comment by i-bash** [comment]
Добавил проверки на наличие столбца onhand_qty.
